/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kitchen_recognition_constant_MouseRecognition */

#ifndef _Included_com_kitchen_recognition_constant_Recognition
#define _Included_com_kitchen_recognition_constant_Recognition
#ifdef __cplusplus
extern "C" {
#endif
/*
 */

JNIEXPORT void JNICALL Java_com_kitchen_recognition_constant_Recognition_PushFrame
(JNIEnv *, jobject , jlong , jstring ,jbyteArray);

JNIEXPORT jobject JNICALL Java_com_kitchen_recognition_constant_Recognition_SendFrame
(JNIEnv *, jobject );

JNIEXPORT void JNICALL Java_com_kitchen_recognition_constant_Recognition_SendFrame
(JNIEnv *, jobject ,jobject );


JNIEXPORT jobject JNICALL Java_com_kitchen_recognition_constant_Recognition_SendObject
(JNIEnv *, jobject );


#ifdef __cplusplus
}
#endif
#endif
